require("dotenv").config();

module.exports = {
  PORT:           process.env.PORT || 3000,
  BASE_URL:       process.env.BASE_URL || "https://telegrambot-pkm0.onrender.com",
  TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  CLIENT_ID:      process.env.CLIENT_ID,
  CLIENT_SECRET:  process.env.CLIENT_SECRET,
  REFRESH_TOKEN:  process.env.REFRESH_TOKEN,
  SUPABASE_URL:   process.env.SUPABASE_URL,
  SUPABASE_KEY:   process.env.SUPABASE_KEY,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,

  GEMINI_MODEL:   "gemini-3.5-flash",

  FALLBACK_MODELS: [
    "gemini-3.5-flash",
    "gemini-3.1-flash-lite",
    "gemini-3-flash-preview",
    "gemini-2.5-flash-lite",
    "gemini-2.0-flash-lite",
    "gemini-flash-latest"
  ],

  MAX_THREADS:      30,
  MAX_EMAILS:       60,
  BODY_BUDGET:      2000,
  CACHE_TTL:        30 * 60 * 1000,
  EMAIL_CACHE_TTL:  60 * 1000,
  USER_DAILY_LIMIT: 10,

  KNOWN_SENDERS: [
    "from:scapiacards@federalbank.co.in",
    "from:alerts@hdfcbank.bank.in",
    "from:alerts@hdfcbank.net",
    "from:alerts@icicibank.com",
    "from:sbicard.com",
    "from:alerts@axisbank.com",
    "from:noreply@kotak.com",
    "from:alerts@indusind.com",
    "from:yesbank.in",
    "from:alerts@idfcfirstbank.com",
    "from:noreply@zomato.com",
    "from:noreply@swiggy.in",
    "from:auto-confirm@amazon.in",
    "from:shipment-tracking@amazon.in",
    "from:bookingconfirmation@bookmyshow.com",
    "from:noreply@bookmyshow.com",
    "from:tickets@pvrinemas.com",
    "from:noreply@pvrinemas.com",
    "from:noreply@inoxmovies.com",
    "from:tickets@ixigo.com",
    "from:bookings@makemytrip.com",
    "from:noreply@cleartrip.com",
    "from:tickets@irctc.co.in",
    "from:noreply@redbus.in",
    "from:calendar-notification@google.com",
    "from:creditcardstatement@mail.hsbc.co.in",
"from:creditcard.estatements@indusind.com",
"from:estatements@aubank.in",
"from:cc.statements@axis.bank.in",
  ],
};
